apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatbot-builder-ingress
  labels:
    name: chatbot-builder-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-issuer"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - bot-touristant.abcdavid.net
      secretName: chatbot-builder-ayw744-tls
  rules:
    - host: bot-touristant.abcdavid.net
      http:
        paths:
          - pathType: Prefix
            path: "/(.*)"
            backend:
              service:
                name: chatbot-builder-fe-mvp-service
                port:
                  number: 8501

          - pathType: Prefix
            path: "/api/(.*)"
            backend:
              service:
                name: chatbot-builder-be-service
                port:
                  number: 8000
