apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatbot-builder
resources:
  - env-secret.yaml
  - volume-claim.yaml
  - redis.yaml
  - postgres.yaml
  - qdrant.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
