# docker compose -p assistant-builder-dev -f docker-compose-dev.yml --env-file .env.dev up

services:
  db-postgres:
    image: postgres:15
    restart: no
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'

  db-redis:
    image: redis:7
    restart: no
    ports:
      - '6379:6379'
    command: 'redis-server --save 120 1 --loglevel warning --requirepass ${REDIS_PASSWORD}'