# docker compose -p assistant-builder-staging -f docker-compose-staging.yml --env-file .env.staging up

services:
  db-postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'

  db-redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - '127.0.0.1:6379:6379'
    command: 'redis-server --save 120 1 --loglevel warning --requirepass ${REDIS_PASSWORD}'

  app-backend:
    build:
      context: .
      dockerfile: Dockerfile-staging
    restart: unless-stopped
    ports:
      - '127.0.0.1:8000:8000'
    env_file:
      - .env.staging
    depends_on:
      - db-postgres
      - db-redis
